version: "3"
services:
    bot:
        build: .
        restart: unless-stopped
        depends_on:
            - mariadb
        links:
            - mariadb
        networks:
            - backend
        env_file:
            - .env
    mariadb:
        image: mariadb:10.7.3
        restart: always
        expose:
            # Opens port 3306 on the container
            - '3306'
        volumes:
            - "/var/lib/mysql/data:${MARIADB_DATA_DIR}"
            - "/var/lib/mysql/logs:${MARIADB_LOG_DIR}"
            - db:/data/ploxy
        env_file: 
            - .env
        networks:
            - backend
networks:
    backend:
        driver: bridge
