version: "3"
services:
    bot:
        build: .
        restart: unless-stopped
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - backend
        env_file:
            - .env
    postgres:
        image: postgres:14.1
        restart: always
        ports:
            # <Port exposed> : < Port inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
        volumes:
            - db:/data/ploxy
        env_file: 
            - .env
        networks:
            - backend
networks:
    backend:
        driver: bridge

volumes:
    db: {}
