version: "3"
services:
    bot:
        build: .
        restart: unless-stopped
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - backend
        env_file:
            - .env
    postgres:
        image: postgres:14.1
        restart: always
        ports:
            # <Port exposed> : < Port inside container>
            - '5432:5432'
        expose:
            # Opens port 5432 on the container
            - '5432'
        volumes:
            - db:/data/ploxy
        env_file: 
            - .env
        networks:
            - backend
networks:
    backend:
        driver: bridge

volumes:
    db: {}
